version: "3.1"
services:

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todo
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=123456
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3306:3306"

  webserver:
    build:
      context: ./docker/webserver/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/
    ports:
      - "8387:80"

